[tool.poetry]
name = "django-test"
version = "0.1.0"
description = ""
authors = ["hasnain <hasnain@zeropoint.hr>"]
readme = "readme.md"

[tool.poetry.dependencies]
python = "^3.8"
django = "^4.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
